Matrix as NumPy Array

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
M = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Adding two matrices

In [4]:
A = np.array([
    [1, 2],
    [3, 4]
    ])
B = np.array([
    [5, 6],
    [7, 8]
    ])
C = A + B
C

array([[ 6,  8],
       [10, 12]])

Scaling a matrix

In [5]:
M = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
    ])
3 * M

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

Element wise multiplication of matrices

In [6]:
A = np.array([
    [1, 2],
    [3, 4]
    ])
B = np.array([
    [5, 6],
    [7, 8]
    ])
A * B

array([[ 5, 12],
       [21, 32]])

Element wise functions of matrices
- Example 1: f(x) = |x|

In [7]:
A = np.array([
    [-1, 2],
    [-3, -4]
    ])
np.abs(A)

array([[1, 2],
       [3, 4]])

In [8]:
np.abs(np.array([-1, -2, 3, -4]))

array([1, 2, 3, 4])

- Example 2: Bij = (Aij)^2

In [9]:
A = np.array([
    [1, np.sqrt(2)],
    [np.sqrt(3), 2]
    ])
B = A ** 2
B

array([[1., 2.],
       [3., 4.]])

Transpose of a matrix

In [15]:
M = np.array([
    [1, 2, 3], 
    [4, 5, 6]
    ])
M.T # or np.transpose(M) or M.transpose()


array([[1, 4],
       [2, 5],
       [3, 6]])

Shape and dimension of a matrix
- M is a two-dimensional Numpy array with shape (2, 3)

In [16]:
M = np.array([
    [1, 2, 3], 
    [4, 5, 6]
    ])
M.shape

(2, 3)

In [17]:
M.ndim

2

Vectors as Matrices

In [20]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [22]:
x = np.array([[1, 2, 3]])
x.shape
x


array([[1, 2, 3]])

In [23]:
x = np.array([
    [1],
    [2],
    [3]
])
x.shape
x

array([[1],
       [2],
       [3]])