Import

In [39]:
import numpy as np

Python Lists

In [40]:
x = [1,2,3]
y = [4,5,6]
z = []
for i in range(len(x)):
    z.append(x[i]+y[i])

print(z)

[5, 7, 9]


Vectors as NumPy arrays

In [41]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [42]:
list(range(1,4)) #in python

[1, 2, 3]

In [43]:
x = np.arange(1,4) 
x


array([1, 2, 3])

In [44]:
type(x)

numpy.ndarray

Vector addition

In [45]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = x + y
z

array([5, 7, 9])

Element-wise multiplication

In [46]:
x = np.arange(1, 4)
y = np.arange(4, 7)
z = x * y
z

array([ 4, 10, 18])

Scaling vectors

In [47]:
x = np.arange(1, 4)
y = 3 * x
y

array([3, 6, 9])

Python List VS NumPy Arrays
- Numpy is 70x faster than Python lists for large arrays

In [48]:
x_lists = list(range(1, 1_000_001))
x_numpy = np.arange(1, 1_000_001)

In [56]:
%timeit [2 * comp for comp in x_lists]

223 ms ± 34.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [57]:
%timeit 2 * x_numpy

2.48 ms ± 123 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [58]:
223 / 2.48

89.91935483870968

Element-wise functions of vectors
- Example-1: f(x) = x^2

In [52]:
x = np.arange(1, 5)
y = x ** 2
y

array([ 1,  4,  9, 16])

- Example-2.1: f(x) = log(x)

In [53]:
x = np.array([1, 10, 100, 1000, 10_000, 100_000, 1_000_000])
y = np.log10(x)
y

array([0., 1., 2., 3., 4., 5., 6.])

- Example-2.2: f(x) = ln(x) element-wise

In [54]:
x = np.array([1, np.e, np.e ** 2, np.e ** 3, np.e ** 4])
y = np.log(x)
y

array([0., 1., 2., 3., 4.])

- Example-3: f(x) = x + c where c is 5.

In [59]:
x = np.array([1,2,3])
c = 5
y = x + c
y

array([6, 7, 8])

- Example-5: f(x) = 5x - 2

In [63]:
x = np.arange(-1, 3)
y = 5 * x - 2
y

array([-7, -2,  3,  8])

Dot product of vectors

In [ ]:
x = np.arange(1, 5)
y = np.arange(-4, -8, -1)
x @ y 


np.int64(-60)

In [67]:
np.dot(x, y)

np.int64(-60)

Vector of ones and zeros

In [73]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [74]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [76]:
fives = np.ones(5) * 5
fives

array([5., 5., 5., 5., 5.])

Norms of vectors

In [77]:
x = np.array([1,2,3])
np.linalg.norm(x)  # Euclidean norm (L2 norm)

np.float64(3.7416573867739413)

In [78]:
x = np.array([1,2,3])
np.linalg.norm(x, ord=1)  # L1 norm

np.float64(6.0)

Shape and dimensions of vectors
- Shape of a vector is (n, ) where n is the number of elements in the vector
- Dimension of a vector: 1

In [79]:
x = np.array([1,2,3,4])
x.shape

(4,)

In [80]:
x.ndim

1